language: elixir
sudo: required
cache:
  directories:
    - deps
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - docker-ce
elixir:
  - 1.6.6
otp_release:
  - 20.3.8
notifications:
  slack:
    rooms:
      - secure: "cWJ7sOlCgi0ohKOW/72dC8m56S8RMlIWg80+GE0tSjTKqNleCLlqQkk2v2SaVqzXj62cOy26WF3XCCPOnZP/yh3KYE7TJiwaKI95wPjVWpZfMIMWW+TgP09tPei2UrJ9On3wIkJlDTh9OkPXzSEfrT3y18XTYJfxvtaDbnfaVgVPRSkaKNNKF6lj1TfZFsHvwmSIwJWYjJyuCW0AMDAyqdU8ZyCLwSOP6QuE0OMCe/DKHgYtScY4EP+X6kymhUgjeraS7LrColQFh9atKOnFOmUa1pMNCGhfd+lu/PwwCI9IOH+gDqBMntpWqgDcbE0KgxX5JZYlC0swxwKiJ5NVN5GusMyc6WgQu4aoHXEZKOl0ZQNQk8h1G+Xw97E2CxSog9Eudn2wtJ1LyLeIByxONaTU+//thlZd3R+2s+MAZtzwVc0YJ6v6j6cN8jrxGHfv1xExe97pYGR8J5W9asnou/jQdaMb+MYZwkXwQHLU7A4d3IOPPhc57JdgoAriK6agsKNIEVOivHHP2rRg0dN8dm4PAhAal0wwT7uXkpClC08zWUX+5DXYUfU6fGisdVI3J3zRIgfTaXgRzTxO22FmnKcePw+IAJ1MFaUfm5RqqGrLsihD3zodQ3IMZBaj2pbE2s+/4QMEWa4ZGb8REaKW1T0+oTL+N0M8yBxFytqzt0o="
    on_success: always
env:
  global:
    - MIX_ENV=test
    - DOCKER_NAMESPACE=edenlabllc
    - APPS='{"uaddresses_api":"uaddresses"}'
    - POSTGRES_VERSION=9.6
    # Docker and GitHub credentials
    - secure: "U6GUrHzmpX/kRNU5DcD8v/X284rW/tOLfCUYc9JvA7gLU0fiJnCtbECNT2JA7Ty4yZWxMlqjkrF4Z2BH/c9VpbK+fZSD9e0kDhTq7BpblT1D9HSdagc1ngqsc1Ksymu69e8V92Yn0EM4fzxo/tMEBOO3VEZhwxa5wO0SWtleUFY+w83yjAzShiy4EaNpwe5JA5qqfZWBh/G/6+li3NRdkPuKBW4N0ZF4Q1rJkOjNLDsOhNMrYv7Bsnn0ekxvXwKql6iUHn02HyvOK3nB5wHlocUnqNiG4wtV9nbwhAsns3rkodGTniV1KGpOiqDAe/lUSxDSnIDOuHvI/PGvbyfj27aF35RUWmic4v7jOULV8m8pUJmp8kJJEW9lWmhM3gMGEhGnMitf7Uo4X4GgxyEXG2mL8A4bucZp5ZrdCTlvr61KpHERkAWtCQpSHGt+mJW2bTxbdFhaTVUoh3ufblozPAnewffyEDK8FLrFe3bV+4JdE53qcx/D4N36EgHYc/DIHKhydlDKvQ6rwelm+QDP7/DB0AFpWHbB3YHGMsLwA5VyW/wpZWKQJKX7wek15UIGNwwJQjOc7GCfGfb1itTxEYmSOYTKmYEXZDq4MMDeI0IBd8kvUtjXJ++NLzWmfx0TgLqA1xH08RiuvZWoAt6r9k6VOvpjFwBgvCYjp16rf4Y="
    - secure: "i+ddATLtEYSThWtPatl9u8J269kCmq0+ekksflJ+FZH14l4iM1LBxT85XnsXoQVA7sIs3Q2oMJa0msnF/KFLmmnnM23fneqt/2YQi2cz7lFj/SHdDkjLraUkQFdXfW4rcVqVEYtrL7lbH+PBlUxg8MdNMol0Jany1g0Lq9tulJPa/vvb2xHin7cUQruWprollG0qoRJihOX9+kCVtvtzD4fPtuhw319HlpzdmELd6F906+1h0wsVv9MAS3M/Mu1lN+UqjIzXxg1SdCOffU4PLzYwjQG6fDV1xoVr2mV9d+cn+OO7OPzehBjX6EJ3CC7ufTDopnjkJqQ0gIFuhdDWB/ndS0L+gAupzD3yMM01XasTaJUq5Gho+DKvM8SKCt4Ka7KJepvY2fNG27A2ZPJHXxJ0RSXciEvUl79YlIO3oTlku9tuDRqDf8EY/SrZ6LhmwuY+LASaQpviTO2wg+Np+glfp5abKUU4QG1qfzDzNxyTaTdDxwS8lywOP4vqC2Jw3oHyXWwEsz0ZEiFESguzkpj+pi6opzgIOUf7NKKWBujoQxYzE9/E6/VnrjVzBX7GCox87jjmFPA+Zhzu0m86DHWq+mN3nedyzPN6RQ3gkm+KBPQElttcqSFurWzirV54F77l1pvniRlCf3+9Oq/0/FjglraDuk67Eew0v/BWcfs="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
- sudo apt-get install jq
- curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/init-db.sh -o init-db.sh; sudo sh ./init-db.sh
jobs:
  include:
    - stage: "test and build"
      # run tests
      script: (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/tests.sh -o tests.sh; bash ./tests.sh) || travis_terminate 1
      # Build Docker container
    - stage: "test and build"
      # "Decrypting deploy key..."
      script:
      - openssl aes-256-cbc -K $encrypted_5e26fd72208f_key -iv $encrypted_5e26fd72208f_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/docker.sh -o docker.sh; bash ./docker.sh) || travis_terminate 1
