version: '3.7'

services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: uaddresses_api_development
    container_name: application
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    volumes:
      - .:/uaddresses.api:cached

  postgres:
    image: postgis/postgis:11-2.5
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres:
